#!/bin/sh -x

set -e

echo "Create Service DATABASES"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE DATABASE ${SERVICE_DB};
EOSQL


echo "Create Service User"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SERVICE_DB" <<-EOSQL
CREATE ROLE ${SERVICE_USER} WITH LOGIN;
ALTER USER ${SERVICE_USER} WITH ENCRYPTED PASSWORD '${SERVICE_PASSWORD}';

ALTER DATABASE ${SERVICE_DB} OWNER TO ${SERVICE_USER};
ALTER SCHEMA public OWNER TO ${SERVICE_USER};
EOSQL

