spring:
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:65432/goodex_data
    username: service_ms
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect