---
spring:
  application:
    name: service
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:65432/goodex_data
    username: service_ms
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  es:
    hostandport: "localhost:9200"
    username: "elastic"
    password: "changeme"
  kafka:
    bootstrapservers: "localhost:29092"
    producer:
      client-id: "goodex_service"
server:
  port: 8080
logging:
  level:
    ROOT: INFO

spring.thymeleaf.prefix: "classpath:/templates/"
