spring:
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Goodex_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: "kafka:9092"
    producer:
      client-id: "goodex_service"
server:
  port: 8080
