spring:
  mail:
    host: smtp.yandex.ru
    username: GoodexSN@yandex.ru
    password: zyxxohybnahriluo
    port: 587
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
  application:
    name: web
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Goodex
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  header: Authorization
  secret: bookingcar
  expiration: 425000


# ВСТАВИТЬ СВОЙ АБСОЛЮТНЫЙ ПУТЬ ДО img!!!
upload:
  path: ###

server:
  port: 8082
