spring:
  mail:
    host: smtp.yandex.ru
    username: GoodexSN@yandex.ru
    password: zyxxohybnahriluo
    port: 587
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
  application:
    name: web
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:65432/auth
    username: web_ms
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  header: Authorization
  secret: bookingcar
  expiration: 425000
  serviceUsername: serviceUsername
  serviceExpiration: 60

eureka:
  client:
    serviceUrl.defaultZone: "http://127.0.0.1:8761/eureka/"
    enabled: "true"

# ВСТАВИТЬ СВОЙ АБСОЛЮТНЫЙ ПУТЬ ДО img!!!
upload:
  path: ###

server:
  port: 8082

baselink: http://localhost:8080
